#!/bin/bash

set -e

printf '\npost-checkout hook\n\n'

prevHEAD=$1
newHEAD=$2
checkoutType=$3
newBranch=`git reflog | awk 'NR==1{ print $8; exit }'`

if [ "$newBranch" = "main" ]; then
  amplify checkout env prod
elif [ "$newBranch" = "stage" ]; then
  amplify checkout env stage
elif [ "$newBranch" = "test" ]; then
  amplify checkout env test
else
  amplify checkout env dev
fi
